### ISSUE TITLE
bot-test-app Crashed

### ISSUE THREAD

**Issue by nsand** [nsand/issue_dump#1]
`bot-test-app` crashed at **2016-06-01T16:51:57Z**
## Metadata

```
{"instance":"c179e1d212484fcaa64b20e6e32bdc68","index":0,"exit_status":1,"exit_description":"app instance exited","reason":"CRASHED"}
```
## Recent Logs

```
01 Jun 12:51:57 [App/0] ERR /home/vcap/app/app.js:11
01 Jun 12:51:57 [App/0] ERR     some.that.does.not.exist(0);
01 Jun 12:51:57 [App/0] ERR     ^
01 Jun 12:51:57 [App/0] ERR ReferenceError: some is not defined
01 Jun 12:51:57 [App/0] ERR     at crashIt (/home/vcap/app/app.js:11:2)
01 Jun 12:51:57 [App/0] ERR     at wrapper [as _onTimeout] (timers.js:275:11)
01 Jun 12:51:57 [App/0] ERR     at Timer.listOnTimeout (timers.js:92:15)
01 Jun 12:51:57 [RTR/1] OUT bot-test-app.mybluemix.net - [01/06/2016:16:51:57 +0000] "GET /crash HTTP/1.1" 502 0 67 "-" "curl/7.43.0" 108.168.250.152:44854 x_forwarded_for:"129.42.208.184" x_forwarded_proto:"http" vcap_request_id:4121aff1-a3b6-4e20-4a0c-b7e333b633f9 response_time:0.026449334 app_id:b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed x_global_transaction_id:"1635017905"

01 Jun 12:51:57 [API/0] OUT App instance exited with guid b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed payload: {"cc_partition"=>"default", "droplet"=>"b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed", "version"=>"3385bc1a-2510-4dd2-9505-be4601f780e3", "instance"=>"c179e1d212484fcaa64b20e6e32bdc68", "index"=>0, "reason"=>"CRASHED", "exit_status"=>1, "exit_description"=>"app instance exited", "crash_timestamp"=>1464799917}
```

**Comment by nsand** [comment]
`bot-test-app` crashed at **2016-06-01T17:04:39Z**

## Metadata

```
{"instance":"531a36e46f0b4418ae4775e56ba21da5","index":1,"exit_status":1,"exit_description":"app instance exited","reason":"CRASHED"}
```

## Recent Logs

```
01 Jun 12:51:57 [App/0] ERR /home/vcap/app/app.js:11
01 Jun 12:51:57 [App/0] ERR     some.that.does.not.exist(0);
01 Jun 12:51:57 [App/0] ERR     ^
01 Jun 12:51:57 [App/0] ERR ReferenceError: some is not defined
01 Jun 12:51:57 [App/0] ERR     at crashIt (/home/vcap/app/app.js:11:2)
01 Jun 12:51:57 [App/0] ERR     at wrapper [as _onTimeout] (timers.js:275:11)
01 Jun 12:51:57 [App/0] ERR     at Timer.listOnTimeout (timers.js:92:15)
01 Jun 12:51:57 [RTR/1] OUT bot-test-app.mybluemix.net - [01/06/2016:16:51:57 +0000] "GET /crash HTTP/1.1" 502 0 67 "-" "curl/7.43.0" 108.168.250.152:44854 x_forwarded_for:"129.42.208.184" x_forwarded_proto:"http" vcap_request_id:4121aff1-a3b6-4e20-4a0c-b7e333b633f9 response_time:0.026449334 app_id:b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed x_global_transaction_id:"1635017905"

01 Jun 12:51:57 [API/0] OUT App instance exited with guid b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed payload: {"cc_partition"=>"default", "droplet"=>"b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed", "version"=>"3385bc1a-2510-4dd2-9505-be4601f780e3", "instance"=>"c179e1d212484fcaa64b20e6e32bdc68", "index"=>0, "reason"=>"CRASHED", "exit_status"=>1, "exit_description"=>"app instance exited", "crash_timestamp"=>1464799917}
01 Jun 12:52:44 [DEA/74]    OUT Starting app instance (index 0) with guid b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed
01 Jun 12:52:58 [App/0] OUT server starting on https://bot-test-app.mybluemix.net
01 Jun 12:59:36 [DEA/49]    OUT Removing crash for app with id b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed
01 Jun 12:59:36 [DEA/49]    OUT Stopping app instance (index 1) with guid b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed
01 Jun 12:59:36 [DEA/49]    OUT Stopped app instance (index 1) with guid b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed
01 Jun 13:04:39 [App/1] ERR /home/vcap/app/app.js:11
01 Jun 13:04:39 [App/1] ERR     some.that.does.not.exist(0);
01 Jun 13:04:39 [App/1] ERR     ^
01 Jun 13:04:39 [App/1] ERR ReferenceError: some is not defined
01 Jun 13:04:39 [App/1] ERR     at crashIt (/home/vcap/app/app.js:11:2)
01 Jun 13:04:39 [App/1] ERR     at wrapper [as _onTimeout] (timers.js:275:11)
01 Jun 13:04:39 [App/1] ERR     at Timer.listOnTimeout (timers.js:92:15)
01 Jun 13:04:39 [RTR/1] OUT bot-test-app.mybluemix.net - [01/06/2016:17:04:39 +0000] "GET /crash HTTP/1.1" 502 0 67 "-" "curl/7.43.0" 108.168.250.156:56987 x_forwarded_for:"129.42.208.184" x_forwarded_proto:"http" vcap_request_id:43f0c73d-2992-4f74-7256-f19f9c291e8c response_time:0.024944132 app_id:b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed x_global_transaction_id:"2060204525"

01 Jun 13:04:39 [API/7] OUT App instance exited with guid b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed payload: {"cc_partition"=>"default", "droplet"=>"b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed", "version"=>"3385bc1a-2510-4dd2-9505-be4601f780e3", "instance"=>"531a36e46f0b4418ae4775e56ba21da5", "index"=>1, "reason"=>"CRASHED", "exit_status"=>1, "exit_description"=>"app instance exited", "crash_timestamp"=>1464800679}
```

**Comment by nsand** [comment]
`bot-test-app` crashed at **2016-06-01T17:20:57Z**

## Metadata

```
{"instance":"25374530d3044892bc33ac03991b954c","index":0,"exit_status":1,"exit_description":"app instance exited","reason":"CRASHED"}
```

## Recent Logs

```
01 Jun 16:51:57 UTC [App/0] ERR /home/vcap/app/app.js:11
01 Jun 16:51:57 UTC [App/0] ERR     some.that.does.not.exist(0);
01 Jun 16:51:57 UTC [App/0] ERR     ^
01 Jun 16:51:57 UTC [App/0] ERR ReferenceError: some is not defined
01 Jun 16:51:57 UTC [App/0] ERR     at crashIt (/home/vcap/app/app.js:11:2)
01 Jun 16:51:57 UTC [App/0] ERR     at wrapper [as _onTimeout] (timers.js:275:11)
01 Jun 16:51:57 UTC [App/0] ERR     at Timer.listOnTimeout (timers.js:92:15)
01 Jun 16:51:57 UTC [RTR/1] OUT bot-test-app.mybluemix.net - [01/06/2016:16:51:57 +0000] "GET /crash HTTP/1.1" 502 0 67 "-" "curl/7.43.0" 108.168.250.152:44854 x_forwarded_for:"129.42.208.184" x_forwarded_proto:"http" vcap_request_id:4121aff1-a3b6-4e20-4a0c-b7e333b633f9 response_time:0.026449334 app_id:b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed x_global_transaction_id:"1635017905"

01 Jun 16:51:57 UTC [API/0] OUT App instance exited with guid b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed payload: {"cc_partition"=>"default", "droplet"=>"b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed", "version"=>"3385bc1a-2510-4dd2-9505-be4601f780e3", "instance"=>"c179e1d212484fcaa64b20e6e32bdc68", "index"=>0, "reason"=>"CRASHED", "exit_status"=>1, "exit_description"=>"app instance exited", "crash_timestamp"=>1464799917}
01 Jun 16:52:44 UTC [DEA/74]    OUT Starting app instance (index 0) with guid b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed
01 Jun 16:52:58 UTC [App/0] OUT server starting on https://bot-test-app.mybluemix.net
01 Jun 16:59:36 UTC [DEA/49]    OUT Removing crash for app with id b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed
01 Jun 16:59:36 UTC [DEA/49]    OUT Stopping app instance (index 1) with guid b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed
01 Jun 16:59:36 UTC [DEA/49]    OUT Stopped app instance (index 1) with guid b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed
01 Jun 17:04:39 UTC [App/1] ERR /home/vcap/app/app.js:11
01 Jun 17:04:39 UTC [App/1] ERR     some.that.does.not.exist(0);
01 Jun 17:04:39 UTC [App/1] ERR     ^
01 Jun 17:04:39 UTC [App/1] ERR ReferenceError: some is not defined
01 Jun 17:04:39 UTC [App/1] ERR     at crashIt (/home/vcap/app/app.js:11:2)
01 Jun 17:04:39 UTC [App/1] ERR     at wrapper [as _onTimeout] (timers.js:275:11)
01 Jun 17:04:39 UTC [App/1] ERR     at Timer.listOnTimeout (timers.js:92:15)
01 Jun 17:04:39 UTC [RTR/1] OUT bot-test-app.mybluemix.net - [01/06/2016:17:04:39 +0000] "GET /crash HTTP/1.1" 502 0 67 "-" "curl/7.43.0" 108.168.250.156:56987 x_forwarded_for:"129.42.208.184" x_forwarded_proto:"http" vcap_request_id:43f0c73d-2992-4f74-7256-f19f9c291e8c response_time:0.024944132 app_id:b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed x_global_transaction_id:"2060204525"

01 Jun 17:04:39 UTC [API/7] OUT App instance exited with guid b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed payload: {"cc_partition"=>"default", "droplet"=>"b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed", "version"=>"3385bc1a-2510-4dd2-9505-be4601f780e3", "instance"=>"531a36e46f0b4418ae4775e56ba21da5", "index"=>1, "reason"=>"CRASHED", "exit_status"=>1, "exit_description"=>"app instance exited", "crash_timestamp"=>1464800679}
01 Jun 17:05:10 UTC [DEA/86]    OUT Starting app instance (index 1) with guid b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed
01 Jun 17:05:23 UTC [App/1] OUT server starting on https://bot-test-app.mybluemix.net
01 Jun 17:20:57 UTC [App/0] ERR /home/vcap/app/app.js:11
01 Jun 17:20:57 UTC [App/0] ERR     some.that.does.not.exist(0);
01 Jun 17:20:57 UTC [App/0] ERR     ^
01 Jun 17:20:57 UTC [App/0] ERR ReferenceError: some is not defined
01 Jun 17:20:57 UTC [App/0] ERR     at crashIt (/home/vcap/app/app.js:11:2)
01 Jun 17:20:57 UTC [App/0] ERR     at wrapper [as _onTimeout] (timers.js:275:11)
01 Jun 17:20:57 UTC [App/0] ERR     at Timer.listOnTimeout (timers.js:92:15)
01 Jun 17:20:57 UTC [RTR/3] OUT bot-test-app.mybluemix.net - [01/06/2016:17:20:57 +0000] "GET /crash HTTP/1.1" 502 0 67 "-" "curl/7.43.0" 108.168.250.156:31045 x_forwarded_for:"129.42.208.184" x_forwarded_proto:"http" vcap_request_id:a698185a-08ae-4bef-525d-3c2ccb9c6659 response_time:0.020520789 app_id:b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed x_global_transaction_id:"3179023023"

01 Jun 17:20:57 UTC [API/9] OUT App instance exited with guid b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed payload: {"cc_partition"=>"default", "droplet"=>"b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed", "version"=>"3385bc1a-2510-4dd2-9505-be4601f780e3", "instance"=>"25374530d3044892bc33ac03991b954c", "index"=>0, "reason"=>"CRASHED", "exit_status"=>1, "exit_description"=>"app instance exited", "crash_timestamp"=>1464801657}
```

**Comment by nsand** [comment]
`bot-test-app` crashed at **2016-06-01T19:47:27Z**

## Metadata

```
{"instance":"d6ee22084ced4a899fd534517c88e7f8","index":1,"exit_status":1,"exit_description":"app instance exited","reason":"CRASHED"}
```

## Recent Logs

```
01 Jun 18:33:51 UTC [App/1] ERR     ^
01 Jun 18:33:51 UTC [App/1] ERR     at crashIt (/home/vcap/app/app.js:11:2)
01 Jun 18:33:51 UTC [App/1] ERR     at wrapper [as _onTimeout] (timers.js:275:11)
01 Jun 18:33:51 UTC [API/2] OUT App instance exited with guid b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed payload: {"cc_partition"=>"default", "droplet"=>"b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed", "version"=>"3385bc1a-2510-4dd2-9505-be4601f780e3", "instance"=>"37bc03bee7884fc69bfed4807432c4fe", "index"=>1, "reason"=>"CRASHED", "exit_status"=>1, "exit_description"=>"app instance exited", "crash_timestamp"=>1464806031}
01 Jun 18:52:15 UTC [DEA/79]    OUT Removing crash for app with id b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed
01 Jun 18:52:15 UTC [DEA/79]    OUT Stopping app instance (index 0) with guid b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed
01 Jun 18:52:15 UTC [DEA/79]    OUT Stopped app instance (index 0) with guid b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed
01 Jun 19:04:51 UTC [DEA/176]   OUT Removing crash for app with id b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed
01 Jun 19:04:51 UTC [DEA/176]   OUT Stopping app instance (index 1) with guid b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed
01 Jun 19:04:51 UTC [DEA/176]   OUT Stopped app instance (index 1) with guid b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed
01 Jun 19:21:11 UTC [DEA/74]    OUT Removing crash for app with id b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed
01 Jun 19:21:11 UTC [DEA/74]    OUT Stopping app instance (index 0) with guid b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed
01 Jun 19:21:11 UTC [DEA/74]    OUT Stopped app instance (index 0) with guid b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed
01 Jun 19:47:27 UTC [App/1] ERR /home/vcap/app/app.js:11
01 Jun 19:47:27 UTC [App/1] ERR     some.that.does.not.exist(0);
01 Jun 19:47:27 UTC [App/1] ERR     ^
01 Jun 19:47:27 UTC [App/1] ERR ReferenceError: some is not defined
01 Jun 19:47:27 UTC [App/1] ERR     at crashIt (/home/vcap/app/app.js:11:2)
01 Jun 19:47:27 UTC [App/1] ERR     at wrapper [as _onTimeout] (timers.js:275:11)
01 Jun 19:47:27 UTC [App/1] ERR     at Timer.listOnTimeout (timers.js:92:15)
01 Jun 19:47:27 UTC [RTR/0] OUT bot-test-app.mybluemix.net - [01/06/2016:19:47:27 +0000] "GET /crash HTTP/1.1" 502 0 67 "-" "curl/7.43.0" 169.54.202.27:54267 x_forwarded_for:"129.42.208.184" x_forwarded_proto:"http" vcap_request_id:0d616c6b-86f6-418f-4316-4d13340041f5 response_time:0.023576069 app_id:b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed x_global_transaction_id:"1648695719"

01 Jun 19:47:27 UTC [API/5] OUT App instance exited with guid b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed payload: {"cc_partition"=>"default", "droplet"=>"b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed", "version"=>"3385bc1a-2510-4dd2-9505-be4601f780e3", "instance"=>"d6ee22084ced4a899fd534517c88e7f8", "index"=>1, "reason"=>"CRASHED", "exit_status"=>1, "exit_description"=>"app instance exited", "crash_timestamp"=>1464810447}
```

**Comment by nsand** [comment]
`bot-test-app` crashed at **2016-06-01T19:57:03Z**

## Metadata

```
{"instance":"281a6684a883496b9bf8c91b40c35175","index":0,"exit_status":1,"exit_description":"app instance exited","reason":"CRASHED"}
```

## Recent Logs

```
01 Jun 18:33:51 UTC [App/1] ERR     at crashIt (/home/vcap/app/app.js:11:2)
01 Jun 18:33:51 UTC [API/2] OUT App instance exited with guid b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed payload: {"cc_partition"=>"default", "droplet"=>"b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed", "version"=>"3385bc1a-2510-4dd2-9505-be4601f780e3", "instance"=>"37bc03bee7884fc69bfed4807432c4fe", "index"=>1, "reason"=>"CRASHED", "exit_status"=>1, "exit_description"=>"app instance exited", "crash_timestamp"=>1464806031}
01 Jun 18:52:15 UTC [DEA/79]    OUT Removing crash for app with id b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed
01 Jun 19:04:51 UTC [DEA/176]   OUT Removing crash for app with id b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed
01 Jun 19:04:51 UTC [DEA/176]   OUT Stopping app instance (index 1) with guid b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed
01 Jun 19:04:51 UTC [DEA/176]   OUT Stopped app instance (index 1) with guid b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed
01 Jun 19:21:11 UTC [DEA/74]    OUT Removing crash for app with id b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed
01 Jun 19:21:11 UTC [DEA/74]    OUT Stopping app instance (index 0) with guid b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed
01 Jun 19:21:11 UTC [DEA/74]    OUT Stopped app instance (index 0) with guid b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed
01 Jun 19:47:27 UTC [App/1] ERR /home/vcap/app/app.js:11
01 Jun 19:47:27 UTC [App/1] ERR     some.that.does.not.exist(0);
01 Jun 19:47:27 UTC [App/1] ERR     ^
01 Jun 19:47:27 UTC [App/1] ERR ReferenceError: some is not defined
01 Jun 19:47:27 UTC [App/1] ERR     at crashIt (/home/vcap/app/app.js:11:2)
01 Jun 19:47:27 UTC [App/1] ERR     at wrapper [as _onTimeout] (timers.js:275:11)
01 Jun 19:47:27 UTC [App/1] ERR     at Timer.listOnTimeout (timers.js:92:15)
01 Jun 19:47:27 UTC [RTR/0] OUT bot-test-app.mybluemix.net - [01/06/2016:19:47:27 +0000] "GET /crash HTTP/1.1" 502 0 67 "-" "curl/7.43.0" 169.54.202.27:54267 x_forwarded_for:"129.42.208.184" x_forwarded_proto:"http" vcap_request_id:0d616c6b-86f6-418f-4316-4d13340041f5 response_time:0.023576069 app_id:b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed x_global_transaction_id:"1648695719"

01 Jun 19:47:27 UTC [API/5] OUT App instance exited with guid b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed payload: {"cc_partition"=>"default", "droplet"=>"b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed", "version"=>"3385bc1a-2510-4dd2-9505-be4601f780e3", "instance"=>"d6ee22084ced4a899fd534517c88e7f8", "index"=>1, "reason"=>"CRASHED", "exit_status"=>1, "exit_description"=>"app instance exited", "crash_timestamp"=>1464810447}
01 Jun 19:47:54 UTC [DEA/29]    OUT Starting app instance (index 1) with guid b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed
01 Jun 19:48:10 UTC [App/1] OUT server starting on https://bot-test-app.mybluemix.net
01 Jun 19:57:03 UTC [App/0] ERR /home/vcap/app/app.js:11
01 Jun 19:57:03 UTC [App/0] ERR     some.that.does.not.exist(0);
01 Jun 19:57:03 UTC [App/0] ERR     ^
01 Jun 19:57:03 UTC [App/0] ERR ReferenceError: some is not defined
01 Jun 19:57:03 UTC [App/0] ERR     at crashIt (/home/vcap/app/app.js:11:2)
01 Jun 19:57:03 UTC [App/0] ERR     at wrapper [as _onTimeout] (timers.js:275:11)
01 Jun 19:57:03 UTC [App/0] ERR     at Timer.listOnTimeout (timers.js:92:15)
01 Jun 19:57:03 UTC [RTR/0] OUT bot-test-app.mybluemix.net - [01/06/2016:19:57:03 +0000] "GET /crash HTTP/1.1" 502 0 67 "-" "curl/7.43.0" 108.168.250.155:52749 x_forwarded_for:"129.42.208.184" x_forwarded_proto:"http" vcap_request_id:35a877e3-c731-42ff-6fea-35ef804c517a response_time:0.023305941 app_id:b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed x_global_transaction_id:"3896742471"

01 Jun 19:57:03 UTC [API/3] OUT App instance exited with guid b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed payload: {"cc_partition"=>"default", "droplet"=>"b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed", "version"=>"3385bc1a-2510-4dd2-9505-be4601f780e3", "instance"=>"281a6684a883496b9bf8c91b40c35175", "index"=>0, "reason"=>"CRASHED", "exit_status"=>1, "exit_description"=>"app instance exited", "crash_timestamp"=>1464811023}
```

**Comment by nsand** [comment]
`bot-test-app` crashed at **2016-06-03T17:26:25Z**

## Metadata

```
{"instance":"d7c54e5a5e4b4a81b857fc182e0fbf9e","index":0,"exit_status":1,"exit_description":"app instance exited","reason":"CRASHED"}
```

## Recent Logs

```
03 Jun 17:26:24 UTC [App/0] ERR /home/vcap/app/app.js:11
03 Jun 17:26:24 UTC [App/0] ERR     some.that.does.not.exist(0);
03 Jun 17:26:24 UTC [App/0] ERR     ^
03 Jun 17:26:24 UTC [App/0] ERR ReferenceError: some is not defined
03 Jun 17:26:24 UTC [App/0] ERR     at crashIt (/home/vcap/app/app.js:11:2)
03 Jun 17:26:24 UTC [App/0] ERR     at wrapper [as _onTimeout] (timers.js:275:11)
03 Jun 17:26:24 UTC [App/0] ERR     at Timer.listOnTimeout (timers.js:92:15)
03 Jun 17:26:25 UTC [API/7] OUT App instance exited with guid b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed payload: {"cc_partition"=>"default", "droplet"=>"b4ef896d-e6a0-49fc-bca5-c6dd3a5243ed", "version"=>"3385bc1a-2510-4dd2-9505-be4601f780e3", "instance"=>"d7c54e5a5e4b4a81b857fc182e0fbf9e", "index"=>0, "reason"=>"CRASHED", "exit_status"=>1, "exit_description"=>"app instance exited", "crash_timestamp"=>1464974785}
```
